'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ctlCfdiLineas

    '''<summary>
    '''lblNombre control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNombre As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDireccion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDireccion As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCiudad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCiudad As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTelefono control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTelefono As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblRfc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRfc As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txbCantidad1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbCantidad1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkFlete1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkFlete1 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ChkIva1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChkIva1 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txbDescripcion1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbDescripcion1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txbPrecio1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbPrecio1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblImporte1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblImporte1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txbCantidad2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbCantidad2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkFlete2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkFlete2 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ChkIva2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChkIva2 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txbDescripcion2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbDescripcion2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txbPrecio2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbPrecio2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblImporte2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblImporte2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txbCantidad3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbCantidad3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkFlete3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkFlete3 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ChkIva3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChkIva3 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txbDescripcion3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbDescripcion3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txbPrecio3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbPrecio3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblImporte3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblImporte3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txbCantidad4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbCantidad4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkFlete4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkFlete4 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ChkIva4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChkIva4 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txbDescripcion4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbDescripcion4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txbPrecio4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbPrecio4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblImporte4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblImporte4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txbCantidad5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbCantidad5 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkFlete5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkFlete5 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ChkIva5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChkIva5 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txbDescripcion5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbDescripcion5 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txbPrecio5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbPrecio5 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblImporte5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblImporte5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txbCantidad6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbCantidad6 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkFlete6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkFlete6 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ChkIva6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChkIva6 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txbDescripcion6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbDescripcion6 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txbPrecio6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbPrecio6 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblImporte6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblImporte6 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txbCantidad7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbCantidad7 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkFlete7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkFlete7 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ChkIva7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChkIva7 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txbDescripcion7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbDescripcion7 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txbPrecio7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbPrecio7 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblImporte7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblImporte7 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txbCantidad8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbCantidad8 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkFlete8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkFlete8 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ChkIva8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChkIva8 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txbDescripcion8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbDescripcion8 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txbPrecio8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbPrecio8 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblImporte8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblImporte8 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txbCantidad9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbCantidad9 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkFlete9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkFlete9 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ChkIva9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChkIva9 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txbDescripcion9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbDescripcion9 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txbPrecio9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbPrecio9 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblImporte9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblImporte9 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txbCantidad10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbCantidad10 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkFlete10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkFlete10 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ChkIva10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChkIva10 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txbDescripcion10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbDescripcion10 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txbPrecio10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbPrecio10 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblImporte10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblImporte10 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txbCantidad11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbCantidad11 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkFlete11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkFlete11 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ChkIva11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChkIva11 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txbDescripcion11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbDescripcion11 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txbPrecio11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbPrecio11 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblImporte11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblImporte11 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txbCantidad12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbCantidad12 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkFlete12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkFlete12 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ChkIva12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChkIva12 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txbDescripcion12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbDescripcion12 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txbPrecio12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbPrecio12 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblImporte12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblImporte12 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txbCantidad13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbCantidad13 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkFlete13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkFlete13 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ChkIva13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChkIva13 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txbDescripcion13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbDescripcion13 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txbPrecio13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbPrecio13 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblImporte13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblImporte13 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txbCantidad14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbCantidad14 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkFlete14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkFlete14 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ChkIva14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChkIva14 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txbDescripcion14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbDescripcion14 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txbPrecio14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbPrecio14 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblImporte14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblImporte14 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txbCantidad15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbCantidad15 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkFlete15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkFlete15 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ChkIva15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChkIva15 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txbDescripcion15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbDescripcion15 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txbPrecio15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbPrecio15 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblImporte15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblImporte15 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSubtotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSubtotal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblIva control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIva As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblRetencion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRetencion As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txbCantidadLetra control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbCantidadLetra As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txbAnotaciones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbAnotaciones As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlFormaPago control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlFormaPago As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlMetodoPago control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlMetodoPago As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txbCtaPago control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbCtaPago As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txbTasaIva control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbTasaIva As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txbTasaRetencion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbTasaRetencion As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rbtnMoneda control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbtnMoneda As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''ddlTipoComprobante control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTipoComprobante As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblMensajeCFDI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMensajeCFDI As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMensajeCBB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMensajeCBB As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMensajePdf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMensajePdf As Global.System.Web.UI.WebControls.Label
End Class
