'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ctlFormatoFacturaAmerica

    '''<summary>
    '''txbDia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbDia As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txbMes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbMes As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txbAno control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbAno As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txbNombre control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbNombre As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txbDireccion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbDireccion As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txbCiudad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbCiudad As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txbCantidad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbCantidad As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txbDescripcion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbDescripcion As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txbPrecioUnitario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbPrecioUnitario As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txbImporte control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbImporte As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txbCantidadLetra control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbCantidadLetra As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txbTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbTotal As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txbTelefono control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbTelefono As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txbRfc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbRfc As Global.System.Web.UI.WebControls.TextBox
End Class
