'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class NuevaRuta

    '''<summary>
    '''pnlRuta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlRuta As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txbEspecificacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbEspecificacion As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlRuta0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlRuta0 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlRuta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlRuta As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''btnNuevaRuta0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNuevaRuta0 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ddlVehiculo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlVehiculo As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlVehiculo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlVehiculo As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''ddlMoneda control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlMoneda As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlMoneda control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlMoneda As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''ddlEmpresaRuta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlEmpresaRuta As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''EmpresaRuta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EmpresaRuta As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''txbPrecio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbPrecio As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnGuardarRuta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGuardarRuta As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblGuardarRuta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGuardarRuta As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnChildTarget control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnChildTarget As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''mdlChild control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mdlChild As Global.AjaxControlToolkit.ModalPopupExtender

    '''<summary>
    '''pnlChild control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlChild As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txbRuta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbRuta As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txbAbre control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbAbre As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlTipoRuta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTipoRuta As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlTipoRuta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlTipoRuta As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''txbKms control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbKms As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txbTiempo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbTiempo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnGuardarRuta0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGuardarRuta0 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblRuta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRuta As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnCloseChild control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCloseChild As Global.System.Web.UI.WebControls.Button
End Class
