'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CtlSubcuentas

    '''<summary>
    '''txbCuentaPadre control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbCuentaPadre As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txbCuentaIntermedia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbCuentaIntermedia As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txbCuentaHija control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbCuentaHija As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblCuenta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCuenta As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNombreCuenta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNombreCuenta As Global.System.Web.UI.WebControls.Label
End Class
