'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace ServicioIntegracionReference
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.CollectionDataContractAttribute(Name:="ArrayOfAnyType", [Namespace]:="http://localhost/", ItemName:="anyType"),  _
     System.SerializableAttribute()>  _
    Public Class ArrayOfAnyType
        Inherits System.Collections.Generic.List(Of Object)
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://localhost/", ConfigurationName:="ServicioIntegracionReference.TimbradoSoap")>  _
    Public Interface TimbradoSoap
        
        'CODEGEN: Generating message contract since element name usuarioIntegrador from namespace http://localhost/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://localhost/RegistraEmisor", ReplyAction:="*")>  _
        Function RegistraEmisor(ByVal request As ServicioIntegracionReference.RegistraEmisorRequest) As ServicioIntegracionReference.RegistraEmisorResponse
        
        'CODEGEN: Generating message contract since element name usuarioIntegrador from namespace http://localhost/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://localhost/TimbraCFDI", ReplyAction:="*")>  _
        Function TimbraCFDI(ByVal request As ServicioIntegracionReference.TimbraCFDIRequest) As ServicioIntegracionReference.TimbraCFDIResponse
        
        'CODEGEN: Generating message contract since element name usuarioIntegrador from namespace http://localhost/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://localhost/CancelaCFDI", ReplyAction:="*")>  _
        Function CancelaCFDI(ByVal request As ServicioIntegracionReference.CancelaCFDIRequest) As ServicioIntegracionReference.CancelaCFDIResponse
        
        'CODEGEN: Generating message contract since element name usuarioIntegrador from namespace http://localhost/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://localhost/ObtieneCFDI", ReplyAction:="*")>  _
        Function ObtieneCFDI(ByVal request As ServicioIntegracionReference.ObtieneCFDIRequest) As ServicioIntegracionReference.ObtieneCFDIResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class RegistraEmisorRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="RegistraEmisor", [Namespace]:="http://localhost/", Order:=0)>  _
        Public Body As ServicioIntegracionReference.RegistraEmisorRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServicioIntegracionReference.RegistraEmisorRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://localhost/")>  _
    Partial Public Class RegistraEmisorRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public usuarioIntegrador As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public rfcEmisor As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public base64Cer As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public base64Key As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public contrasena As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal usuarioIntegrador As String, ByVal rfcEmisor As String, ByVal base64Cer As String, ByVal base64Key As String, ByVal contrasena As String)
            MyBase.New
            Me.usuarioIntegrador = usuarioIntegrador
            Me.rfcEmisor = rfcEmisor
            Me.base64Cer = base64Cer
            Me.base64Key = base64Key
            Me.contrasena = contrasena
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class RegistraEmisorResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="RegistraEmisorResponse", [Namespace]:="http://localhost/", Order:=0)>  _
        Public Body As ServicioIntegracionReference.RegistraEmisorResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServicioIntegracionReference.RegistraEmisorResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://localhost/")>  _
    Partial Public Class RegistraEmisorResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public RegistraEmisorResult As ServicioIntegracionReference.ArrayOfAnyType
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal RegistraEmisorResult As ServicioIntegracionReference.ArrayOfAnyType)
            MyBase.New
            Me.RegistraEmisorResult = RegistraEmisorResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class TimbraCFDIRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="TimbraCFDI", [Namespace]:="http://localhost/", Order:=0)>  _
        Public Body As ServicioIntegracionReference.TimbraCFDIRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServicioIntegracionReference.TimbraCFDIRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://localhost/")>  _
    Partial Public Class TimbraCFDIRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public usuarioIntegrador As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public xmlComprobanteBase64 As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public idComprobante As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal usuarioIntegrador As String, ByVal xmlComprobanteBase64 As String, ByVal idComprobante As String)
            MyBase.New
            Me.usuarioIntegrador = usuarioIntegrador
            Me.xmlComprobanteBase64 = xmlComprobanteBase64
            Me.idComprobante = idComprobante
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class TimbraCFDIResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="TimbraCFDIResponse", [Namespace]:="http://localhost/", Order:=0)>  _
        Public Body As ServicioIntegracionReference.TimbraCFDIResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServicioIntegracionReference.TimbraCFDIResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://localhost/")>  _
    Partial Public Class TimbraCFDIResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public TimbraCFDIResult As ServicioIntegracionReference.ArrayOfAnyType
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal TimbraCFDIResult As ServicioIntegracionReference.ArrayOfAnyType)
            MyBase.New
            Me.TimbraCFDIResult = TimbraCFDIResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class CancelaCFDIRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="CancelaCFDI", [Namespace]:="http://localhost/", Order:=0)>  _
        Public Body As ServicioIntegracionReference.CancelaCFDIRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServicioIntegracionReference.CancelaCFDIRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://localhost/")>  _
    Partial Public Class CancelaCFDIRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public usuarioIntegrador As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public rfcEmisor As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public folioUUID As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal usuarioIntegrador As String, ByVal rfcEmisor As String, ByVal folioUUID As String)
            MyBase.New
            Me.usuarioIntegrador = usuarioIntegrador
            Me.rfcEmisor = rfcEmisor
            Me.folioUUID = folioUUID
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class CancelaCFDIResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="CancelaCFDIResponse", [Namespace]:="http://localhost/", Order:=0)>  _
        Public Body As ServicioIntegracionReference.CancelaCFDIResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServicioIntegracionReference.CancelaCFDIResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://localhost/")>  _
    Partial Public Class CancelaCFDIResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public CancelaCFDIResult As ServicioIntegracionReference.ArrayOfAnyType
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal CancelaCFDIResult As ServicioIntegracionReference.ArrayOfAnyType)
            MyBase.New
            Me.CancelaCFDIResult = CancelaCFDIResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ObtieneCFDIRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ObtieneCFDI", [Namespace]:="http://localhost/", Order:=0)>  _
        Public Body As ServicioIntegracionReference.ObtieneCFDIRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServicioIntegracionReference.ObtieneCFDIRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://localhost/")>  _
    Partial Public Class ObtieneCFDIRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public usuarioIntegrador As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public rfcEmisor As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public folioUUID As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal usuarioIntegrador As String, ByVal rfcEmisor As String, ByVal folioUUID As String)
            MyBase.New
            Me.usuarioIntegrador = usuarioIntegrador
            Me.rfcEmisor = rfcEmisor
            Me.folioUUID = folioUUID
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ObtieneCFDIResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ObtieneCFDIResponse", [Namespace]:="http://localhost/", Order:=0)>  _
        Public Body As ServicioIntegracionReference.ObtieneCFDIResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServicioIntegracionReference.ObtieneCFDIResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://localhost/")>  _
    Partial Public Class ObtieneCFDIResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public ObtieneCFDIResult As ServicioIntegracionReference.ArrayOfAnyType
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ObtieneCFDIResult As ServicioIntegracionReference.ArrayOfAnyType)
            MyBase.New
            Me.ObtieneCFDIResult = ObtieneCFDIResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface TimbradoSoapChannel
        Inherits ServicioIntegracionReference.TimbradoSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class TimbradoSoapClient
        Inherits System.ServiceModel.ClientBase(Of ServicioIntegracionReference.TimbradoSoap)
        Implements ServicioIntegracionReference.TimbradoSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServicioIntegracionReference_TimbradoSoap_RegistraEmisor(ByVal request As ServicioIntegracionReference.RegistraEmisorRequest) As ServicioIntegracionReference.RegistraEmisorResponse Implements ServicioIntegracionReference.TimbradoSoap.RegistraEmisor
            Return MyBase.Channel.RegistraEmisor(request)
        End Function
        
        Public Function RegistraEmisor(ByVal usuarioIntegrador As String, ByVal rfcEmisor As String, ByVal base64Cer As String, ByVal base64Key As String, ByVal contrasena As String) As ServicioIntegracionReference.ArrayOfAnyType
            Dim inValue As ServicioIntegracionReference.RegistraEmisorRequest = New ServicioIntegracionReference.RegistraEmisorRequest()
            inValue.Body = New ServicioIntegracionReference.RegistraEmisorRequestBody()
            inValue.Body.usuarioIntegrador = usuarioIntegrador
            inValue.Body.rfcEmisor = rfcEmisor
            inValue.Body.base64Cer = base64Cer
            inValue.Body.base64Key = base64Key
            inValue.Body.contrasena = contrasena
            Dim retVal As ServicioIntegracionReference.RegistraEmisorResponse = CType(Me,ServicioIntegracionReference.TimbradoSoap).RegistraEmisor(inValue)
            Return retVal.Body.RegistraEmisorResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServicioIntegracionReference_TimbradoSoap_TimbraCFDI(ByVal request As ServicioIntegracionReference.TimbraCFDIRequest) As ServicioIntegracionReference.TimbraCFDIResponse Implements ServicioIntegracionReference.TimbradoSoap.TimbraCFDI
            Return MyBase.Channel.TimbraCFDI(request)
        End Function
        
        Public Function TimbraCFDI(ByVal usuarioIntegrador As String, ByVal xmlComprobanteBase64 As String, ByVal idComprobante As String) As ServicioIntegracionReference.ArrayOfAnyType
            Dim inValue As ServicioIntegracionReference.TimbraCFDIRequest = New ServicioIntegracionReference.TimbraCFDIRequest()
            inValue.Body = New ServicioIntegracionReference.TimbraCFDIRequestBody()
            inValue.Body.usuarioIntegrador = usuarioIntegrador
            inValue.Body.xmlComprobanteBase64 = xmlComprobanteBase64
            inValue.Body.idComprobante = idComprobante
            Dim retVal As ServicioIntegracionReference.TimbraCFDIResponse = CType(Me,ServicioIntegracionReference.TimbradoSoap).TimbraCFDI(inValue)
            Return retVal.Body.TimbraCFDIResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServicioIntegracionReference_TimbradoSoap_CancelaCFDI(ByVal request As ServicioIntegracionReference.CancelaCFDIRequest) As ServicioIntegracionReference.CancelaCFDIResponse Implements ServicioIntegracionReference.TimbradoSoap.CancelaCFDI
            Return MyBase.Channel.CancelaCFDI(request)
        End Function
        
        Public Function CancelaCFDI(ByVal usuarioIntegrador As String, ByVal rfcEmisor As String, ByVal folioUUID As String) As ServicioIntegracionReference.ArrayOfAnyType
            Dim inValue As ServicioIntegracionReference.CancelaCFDIRequest = New ServicioIntegracionReference.CancelaCFDIRequest()
            inValue.Body = New ServicioIntegracionReference.CancelaCFDIRequestBody()
            inValue.Body.usuarioIntegrador = usuarioIntegrador
            inValue.Body.rfcEmisor = rfcEmisor
            inValue.Body.folioUUID = folioUUID
            Dim retVal As ServicioIntegracionReference.CancelaCFDIResponse = CType(Me,ServicioIntegracionReference.TimbradoSoap).CancelaCFDI(inValue)
            Return retVal.Body.CancelaCFDIResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServicioIntegracionReference_TimbradoSoap_ObtieneCFDI(ByVal request As ServicioIntegracionReference.ObtieneCFDIRequest) As ServicioIntegracionReference.ObtieneCFDIResponse Implements ServicioIntegracionReference.TimbradoSoap.ObtieneCFDI
            Return MyBase.Channel.ObtieneCFDI(request)
        End Function
        
        Public Function ObtieneCFDI(ByVal usuarioIntegrador As String, ByVal rfcEmisor As String, ByVal folioUUID As String) As ServicioIntegracionReference.ArrayOfAnyType
            Dim inValue As ServicioIntegracionReference.ObtieneCFDIRequest = New ServicioIntegracionReference.ObtieneCFDIRequest()
            inValue.Body = New ServicioIntegracionReference.ObtieneCFDIRequestBody()
            inValue.Body.usuarioIntegrador = usuarioIntegrador
            inValue.Body.rfcEmisor = rfcEmisor
            inValue.Body.folioUUID = folioUUID
            Dim retVal As ServicioIntegracionReference.ObtieneCFDIResponse = CType(Me,ServicioIntegracionReference.TimbradoSoap).ObtieneCFDI(inValue)
            Return retVal.Body.ObtieneCFDIResult
        End Function
    End Class
End Namespace
